### ------------------------------------------
### //////////////////////////////////////////
### ///// PLUGIN FEITO POR MMT007_BACKUP /////
### //////////////////////////////////////////
### ------------------------------------------

### ------------- Idioma do Plugin -------------
plugin-lang: pt_br


### ------------- Configurações Do Chat -------------
use-join: true
use-leave: true
use-chat: true

### ------------- Blocos Permitidos Para Invasão -------------
use-invasion: true
invasion-blocks:
  - 'ladder'

### ------------- Sistema de Economia -------------
## Abilita Sistema de Econamia
# OBS: REQUER PLUGIN <VAULT>
use-economy: false

## OBS: Use Um Número Negativo Para Dar Dinheiro A Um Player
## Custo De Dominar Chunk
claim-cost: 1000

## Custo De Abandonar Chunk
unclaim-cost: -200

## Custo Extra Por Chunk Dominado
claim-cost-per-chunk: 1250

## Custo Para Criar Facção
faction-create-cost: 5000

### ------------- Config de Facção -------------
## Permite Que O Player Interaja Com Um Mob De Base Inimiga/Neutra
faction-player-interact-entity: false

## Maximo de Caracteres de Nome/Tag da Facção:
faction-max-name-char: 16
faction-max-tag-char: 4

## Quantidade Maxima de players em uma Facção
faction-max-players: 15

## Se Qualquer Player Pode Dominar Um Chunk
faction-player-dominate-chunk: false

## Tamanho Do Mapa De Facção (3x3, 5x5, 10x10, etc...)
faction-map-size: 11
